title: Melate Lottery Analysis
description: Análisis estadístico de Melate, Revancha y Revanchita
theme: jekyll-theme-cayman
markdown: kramdown
# url: "https://mariotristan.github.io"  # opcional
# baseurl: ""  # descomentar si usas un subdirectorio
